//! Embedded completion specs and on-demand materialization to a cache dir.
//!
//! ## Why this exists
//!
//! `ghost-complete` ships with 709 Fig-compatible completion specs baked
//! into the binary. The embedded payload is produced by the crate's
//! `build.rs`, which reads every `specs/*.json`, strips the
//! runtime-unused `js_source` field from generators, re-serialises each
//! spec compactly (no pretty-print whitespace), and writes the result
//! to `$OUT_DIR/specs-min/`. `EMBEDDED_SPECS` itself is generated by
//! the same script and `include!`d from `$OUT_DIR/embedded_specs.rs`.
//! Originally these embedded specs only
//! existed to be copied to disk by `ghost-complete install`. That left a
//! latent bug: a user who ran `cargo install ghost-complete` and then
//! launched `ghost-complete` (without first running `install`) loaded zero
//! specs and got no error — autocomplete silently degraded to filesystem +
//! history + `$PATH` only.
//!
//! This module makes the embedded specs the **runtime fallback** for the
//! spec loader. When the on-disk auto-detection chain in
//! [`crate::spec_dirs::resolve_spec_dirs`] finds no usable directory, the
//! embedded specs are materialized (lazily, once per binary version) into
//! `~/.cache/ghost-complete/embedded-specs/` and that path is appended to
//! the resolved list. From the spec loader's perspective it's just another
//! directory full of JSON; no special-cased "embedded mode" logic is needed
//! downstream.
//!
//! ## Idempotency
//!
//! Materialization writes a `.version` sentinel file containing the binary's
//! `CARGO_PKG_VERSION` plus the embedded spec count, and writes the sentinel
//! LAST so a crash mid-write leaves no sentinel and forces a re-materialize.
//! On every subsequent invocation, if the sentinel matches, the whole call
//! is a single small file read. So the 25 MB of writes happen once per
//! upgrade, not once per process start. This keeps the `<100 ms` startup
//! target intact for the steady state.

use std::io::{self, Write as _};
use std::path::{Path, PathBuf};
use std::sync::atomic::{AtomicU64, Ordering};

// Generated by `build.rs` — spec JSON is minified and has the
// runtime-unused `js_source` field stripped from every generator to
// keep the embedded payload small. See the module doc-comment and
// `build.rs` for details.
include!(concat!(env!("OUT_DIR"), "/embedded_specs.rs"));

/// Path under the user's home where embedded specs are materialized when no
/// other spec directory is available. Kept separate from the `~/.config`
/// install location so a fresh `cargo install` user gets specs without
/// `ghost-complete install`, while still letting an installed user's
/// `~/.config/ghost-complete/specs` take precedence (auto-detection in
/// `spec_dirs::resolve_spec_dirs` checks that path first).
pub fn embedded_cache_dir() -> Option<PathBuf> {
    dirs::home_dir().map(|h| {
        h.join(".cache")
            .join("ghost-complete")
            .join("embedded-specs")
    })
}

/// Sentinel file stored next to the materialized specs. Holds
/// `<crate-version>:<spec-count>` so an upgraded binary that bundles a
/// different spec set forces a refresh, and a partial write that lost some
/// files (count mismatch) also forces a refresh.
fn version_sentinel_contents() -> String {
    format!("{}:{}", env!("CARGO_PKG_VERSION"), EMBEDDED_SPECS.len())
}

/// True iff `dir` already holds the current embedded spec set. The sentinel
/// is written last by [`write_embedded_specs`], so a matching sentinel
/// implies the write completed: a crash mid-write leaves no sentinel (or a
/// stale one), which forces a full re-materialize.
///
/// After the cheap sentinel match, verify the JSON filename set matches the
/// embedded manifest exactly. A sentinel-only check trusts a version string
/// that anyone with write access to `~/.cache/ghost-complete/embedded-specs`
/// can forge; a manifest scan catches both missing-expected-file and
/// unexpected-extra-file cases so a polluted cache is re-materialized even
/// when its sentinel happens to match.
fn embedded_dir_is_current(dir: &Path) -> bool {
    let sentinel = dir.join(".version");
    let Ok(contents) = std::fs::read_to_string(&sentinel) else {
        return false;
    };
    if contents.trim() != version_sentinel_contents() {
        return false;
    }

    let expected: std::collections::HashSet<&str> =
        EMBEDDED_SPECS.iter().map(|(n, _)| *n).collect();
    let Ok(read_dir) = std::fs::read_dir(dir) else {
        return false;
    };

    let mut seen = std::collections::HashSet::with_capacity(expected.len());
    for entry in read_dir.flatten() {
        let path = entry.path();
        if path.extension().and_then(|e| e.to_str()) != Some("json") {
            continue;
        }
        let Some(name) = path.file_name().and_then(|n| n.to_str()) else {
            return false;
        };
        if !expected.contains(name) {
            return false;
        }
        seen.insert(name.to_string());
    }
    seen.len() == expected.len()
}

/// Write every embedded spec into `dir`, creating the directory if needed.
/// Returns the number of files written. Used by both the runtime fallback
/// (via [`materialize_embedded_specs`]) and `ghost-complete install` so the
/// two paths stay byte-identical.
///
/// Purges stale `.json` files before writing. Without this step a previous
/// version's specs (or stray attacker-dropped files) would remain alongside
/// the current set — the sentinel check only verifies `<version>:<count>`,
/// so N stale files + N current files summing to the right count would
/// still look "current".
pub fn write_embedded_specs(dir: &Path) -> io::Result<usize> {
    std::fs::create_dir_all(dir)?;

    // TOCTOU hardening: `materialize_embedded_specs_at` checks that `dir`
    // isn't a symlink before calling us, but an attacker could swap it
    // for a symlink between that check and `create_dir_all` (which
    // happily succeeds against a symlink pointing at an existing dir).
    // Re-check immediately after create_dir_all and refuse to proceed
    // if the dir is now a symlink. This doesn't close the race fully —
    // a directory-fd + openat redesign would — but it eliminates the
    // simple swap window before the subsequent `read_dir` purge walks
    // into attacker-controlled territory.
    if let Ok(meta) = std::fs::symlink_metadata(dir) {
        if meta.file_type().is_symlink() {
            return Err(io::Error::new(
                io::ErrorKind::InvalidInput,
                format!(
                    "refusing to write embedded specs: cache dir {} is a symlink \
                     (possibly swapped after the initial check)",
                    dir.display()
                ),
            ));
        }
    }

    let expected_names: std::collections::HashSet<&str> =
        EMBEDDED_SPECS.iter().map(|(n, _)| *n).collect();
    let read_dir = match std::fs::read_dir(dir) {
        Ok(rd) => rd,
        Err(e) => {
            return Err(io::Error::other(format!(
                "embedded cache purge failed: read_dir({}) errored: {e}",
                dir.display()
            )));
        }
    };
    for entry in read_dir.flatten() {
        let path = entry.path();
        if path.extension().and_then(|e| e.to_str()) != Some("json") {
            continue;
        }
        let name = match path.file_name().and_then(|n| n.to_str()) {
            Some(n) => n,
            None => continue,
        };
        if !expected_names.contains(name) {
            if let Err(e) = std::fs::remove_file(&path) {
                tracing::warn!(
                    "failed to purge stale embedded spec {}: {}",
                    path.display(),
                    e
                );
            }
        }
    }

    let mut count = 0;
    for (idx, (name, contents)) in EMBEDDED_SPECS.iter().enumerate() {
        let dest = dir.join(name);
        // Atomic per-file write via temp-then-rename: `std::fs::write`
        // follows symlinks, which lets a same-user attacker pre-seed
        // `<name>.json` as a symlink to `/etc/passwd` (or any file) and
        // have us truncate the target. `rename` replaces the destination
        // (symlink and all) with our regular file without dereferencing.
        atomic_write(&dest, contents.as_bytes(), idx)?;
        count += 1;
    }
    // Write the sentinel last so a crash mid-write leaves a stale-or-missing
    // sentinel that triggers a re-materialize on the next launch, rather
    // than a fresh sentinel pointing at an incomplete dir. Sentinel goes
    // through the same atomic path so a pre-seeded `.version` symlink
    // can't be followed either.
    atomic_write(
        &dir.join(".version"),
        version_sentinel_contents().as_bytes(),
        EMBEDDED_SPECS.len(),
    )?;
    Ok(count)
}

/// Monotonic counter mixed into the temp-file suffix. Combined with PID
/// and the high-resolution wall-clock nanos, this makes the temp path
/// unpredictable to a same-user attacker racing us between `create_new`
/// and the subsequent `rename`. `create_new(true) + O_NOFOLLOW` is the
/// actual security boundary; the counter just avoids accidental
/// collisions between two atomic writes hitting the same destination
/// name in quick succession from the same process.
static ATOMIC_WRITE_COUNTER: AtomicU64 = AtomicU64::new(0);

/// Write `contents` to `dest` atomically: create a uniquely-named temp
/// file in the same directory with `create_new(true)` + `O_NOFOLLOW`
/// (on Unix), write + fsync, then `rename` it over `dest`.
///
/// Two attack vectors to close:
/// 1. `std::fs::write` follows symlinks, so a same-user attacker who
///    pre-seeds `<name>.json` as a symlink to `/etc/passwd` (or any
///    other user-writable file) gets us to truncate the target. `rename`
///    replaces the destination (symlink and all) with a regular file
///    without dereferencing, closing this vector for the final
///    destination.
/// 2. The temp path itself was previously predictable
///    (`.<file>.tmp.<pid>.<nonce>`) and written with `std::fs::write` —
///    which follows symlinks. Between the `remove_file` and the `write`,
///    an attacker could recreate the temp path as a symlink to an
///    arbitrary target. `create_new(true)` + `O_NOFOLLOW` refuses to
///    open if anything already exists at the temp path (including a
///    symlink), so the race window collapses.
///
/// Cleanup-on-error: any failure after `create_new` succeeds (write,
/// sync, rename) removes the temp file before returning the error.
fn atomic_write(dest: &Path, contents: &[u8], nonce: usize) -> io::Result<()> {
    let parent = dest.parent().ok_or_else(|| {
        io::Error::new(
            io::ErrorKind::InvalidInput,
            "atomic_write: destination has no parent",
        )
    })?;
    let file_name = dest.file_name().ok_or_else(|| {
        io::Error::new(
            io::ErrorKind::InvalidInput,
            "atomic_write: destination has no file name",
        )
    })?;

    // Compose an unpredictable temp name: `.<file>.tmp.<pid>.<nonce>.<nanos>.<ctr>`.
    // PID + nanos + a process-global counter are enough entropy that a
    // same-user attacker can't reliably pre-seed the exact path; the
    // create_new + O_NOFOLLOW below is the real defence, but making
    // the name hard to guess narrows the pre-seeding window further.
    let ctr = ATOMIC_WRITE_COUNTER.fetch_add(1, Ordering::Relaxed);
    let nanos = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_nanos())
        .unwrap_or(0);
    let mut tmp_name = std::ffi::OsString::from(".");
    tmp_name.push(file_name);
    tmp_name.push(format!(
        ".tmp.{}.{}.{}.{}",
        std::process::id(),
        nonce,
        nanos,
        ctr
    ));
    let tmp_path = parent.join(tmp_name);

    let mut opts = std::fs::OpenOptions::new();
    opts.write(true).create_new(true);
    #[cfg(unix)]
    {
        use std::os::unix::fs::OpenOptionsExt;
        // O_NOFOLLOW refuses to open if the final path component is a
        // symlink. Combined with create_new (O_CREAT | O_EXCL) this means
        // the open atomically fails if anything — regular file, directory,
        // symlink, fifo — already exists at tmp_path. No remove-then-write
        // race window.
        opts.custom_flags(libc::O_NOFOLLOW);
        // 0o600: owner-only. The temp file briefly contains the spec
        // contents before rename; no reason for anyone else to read it.
        opts.mode(0o600);
    }

    let mut file = opts.open(&tmp_path)?;
    // Any error after the file is created must clean up the temp file
    // before returning.
    let cleanup = |e: io::Error| -> io::Error {
        if let Err(rm) = std::fs::remove_file(&tmp_path) {
            tracing::warn!("atomic_write leaked temp {}: {}", tmp_path.display(), rm);
        }
        e
    };
    file.write_all(contents).map_err(cleanup)?;
    file.sync_all().map_err(cleanup)?;
    drop(file);
    std::fs::rename(&tmp_path, dest).map_err(cleanup)?;
    Ok(())
}

/// Ensure the embedded-spec cache directory exists and is populated with the
/// current binary's spec set, then return its path. Returns `None` when
/// `dirs::home_dir()` is unavailable (in which case the caller has no
/// fallback path to offer and the embedded specs are unreachable for this
/// run — which matches the pre-fix behavior).
///
/// On the steady-state path (sentinel matches) this is a single small file
/// read — well under a millisecond. The 25 MB write only happens on first
/// use after install or after a version bump.
pub fn materialize_embedded_specs() -> Option<PathBuf> {
    let dir = embedded_cache_dir()?;
    materialize_embedded_specs_at(&dir)
}

/// Testable core of [`materialize_embedded_specs`]: given a caller-chosen
/// directory, refuse to materialise into a symlink, then write out the
/// embedded specs if the sentinel indicates they're stale. Returns the
/// directory on success, or `None` when the symlink guard tripped or the
/// write failed.
fn materialize_embedded_specs_at(dir: &Path) -> Option<PathBuf> {
    // Refuse to materialize into a symlink — an attacker who can create the
    // cache dir could point it at any location on the FS, causing the
    // subsequent `read_dir` + `remove_file` purge in `write_embedded_specs`
    // to follow the link and delete files outside our cache.
    if let Ok(meta) = std::fs::symlink_metadata(dir) {
        if meta.file_type().is_symlink() {
            tracing::warn!(
                dir = %dir.display(),
                "embedded spec cache dir is a symlink; refusing to materialize \
                 (falling back to no on-disk specs for this run)"
            );
            return None;
        }
    }
    if embedded_dir_is_current(dir) {
        return Some(dir.to_path_buf());
    }
    match write_embedded_specs(dir) {
        Ok(count) => {
            tracing::info!(
                count,
                dir = %dir.display(),
                "materialized embedded completion specs to cache directory"
            );
            Some(dir.to_path_buf())
        }
        Err(e) => {
            tracing::warn!(
                error = %e,
                dir = %dir.display(),
                "failed to materialize embedded completion specs — autocomplete will be degraded"
            );
            None
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    #[test]
    fn embedded_specs_slice_is_non_empty() {
        // If this ever fails it means the include_str! table got truncated
        // or the const was emptied — the runtime fallback would silently
        // load zero specs, defeating the binary-embedded fallback entirely.
        assert!(
            !EMBEDDED_SPECS.is_empty(),
            "EMBEDDED_SPECS must not be empty"
        );
        // Sanity: every entry must have a non-empty name and non-empty body.
        for (name, body) in EMBEDDED_SPECS {
            assert!(!name.is_empty(), "embedded spec has empty name");
            assert!(!body.is_empty(), "embedded spec {name} has empty body");
            assert!(
                name.ends_with(".json"),
                "embedded spec {name} should be a .json file"
            );
        }
    }

    #[test]
    fn embedded_specs_preserve_corrected_in_markers() {
        // `build.rs::strip_js_source` must NOT strip `_corrected_in`.
        // That marker is consumed at runtime by `ghost-complete doctor`
        // (crates/ghost-complete/src/doctor.rs::count_corrected_generators_in_spec)
        // to surface generators that were previously mis-converted.
        //
        // WHY this test pins a total: a build-time regression that
        // incidentally dropped `_corrected_in` at any nesting depth would
        // not fail any existing test — every spec would still parse, every
        // generator would still load, but `ghost-complete doctor` would go
        // silent. Walk every embedded spec, count markers, compare to the
        // expected total.
        //
        // Expected count is hard-coded rather than derived from
        // `docs/coverage-baseline.json` because (a) the baseline file is
        // outside this crate and the test would then depend on the workspace
        // layout, and (b) the baseline's `corrected_generators` field is a
        // release-time snapshot that lags the live spec set. If you add or
        // remove `_corrected_in` markers in `specs/`, update this constant
        // and the baseline together in the same PR.
        const EXPECTED_CORRECTED_IN: usize = 171;

        fn count(v: &serde_json::Value) -> usize {
            match v {
                serde_json::Value::Object(map) => {
                    let here = usize::from(map.contains_key("_corrected_in"));
                    here + map.values().map(count).sum::<usize>()
                }
                serde_json::Value::Array(arr) => arr.iter().map(count).sum(),
                _ => 0,
            }
        }

        let total: usize = EMBEDDED_SPECS
            .iter()
            .map(|(name, body)| {
                let v: serde_json::Value = serde_json::from_str(body)
                    .unwrap_or_else(|e| panic!("embedded spec {name} is not valid JSON: {e}"));
                count(&v)
            })
            .sum();

        assert_eq!(
            total, EXPECTED_CORRECTED_IN,
            "embedded specs have {total} `_corrected_in` markers, expected {EXPECTED_CORRECTED_IN}. \
             If you changed a corrected generator, update EXPECTED_CORRECTED_IN and \
             docs/coverage-baseline.json together. If you did NOT intentionally change \
             corrections, build.rs::strip_js_source likely dropped the marker — check its \
             recursion."
        );
    }

    #[test]
    fn write_embedded_specs_writes_all_files_and_sentinel() {
        let tmp = TempDir::new().unwrap();
        let count = write_embedded_specs(tmp.path()).unwrap();
        assert_eq!(count, EMBEDDED_SPECS.len());
        // Every file must be present
        for (name, _) in EMBEDDED_SPECS {
            assert!(
                tmp.path().join(name).exists(),
                "spec {name} was not written"
            );
        }
        // Sentinel must match
        let sentinel = std::fs::read_to_string(tmp.path().join(".version")).unwrap();
        assert_eq!(sentinel, version_sentinel_contents());
    }

    #[test]
    fn embedded_dir_is_current_detects_match() {
        let tmp = TempDir::new().unwrap();
        write_embedded_specs(tmp.path()).unwrap();
        assert!(embedded_dir_is_current(tmp.path()));
    }

    #[test]
    fn embedded_dir_is_current_detects_missing_sentinel() {
        let tmp = TempDir::new().unwrap();
        // Spec files present but no sentinel — must be treated as stale.
        for (name, contents) in EMBEDDED_SPECS.iter().take(3) {
            std::fs::write(tmp.path().join(name), contents).unwrap();
        }
        assert!(!embedded_dir_is_current(tmp.path()));
    }

    #[test]
    fn embedded_dir_is_current_detects_stale_sentinel() {
        let tmp = TempDir::new().unwrap();
        write_embedded_specs(tmp.path()).unwrap();
        // Tamper with the sentinel — older binary version style.
        std::fs::write(tmp.path().join(".version"), "0.0.0:1").unwrap();
        assert!(!embedded_dir_is_current(tmp.path()));
    }

    #[test]
    fn embedded_dir_is_current_rejects_unexpected_json_file() {
        // A sentinel that happens to match the current version does not save
        // a cache directory that was polluted with an extra attacker-dropped
        // JSON file. The manifest scan forces a re-materialize.
        let tmp = TempDir::new().unwrap();
        write_embedded_specs(tmp.path()).unwrap();
        std::fs::write(tmp.path().join("not-a-real-spec.json"), r#"{"name":"x"}"#).unwrap();
        assert!(!embedded_dir_is_current(tmp.path()));
    }

    #[test]
    fn embedded_dir_is_current_rejects_missing_expected_file() {
        // A missing expected file must also force a re-materialize even when
        // the sentinel + total file count would otherwise look plausible.
        let tmp = TempDir::new().unwrap();
        write_embedded_specs(tmp.path()).unwrap();
        let (victim, _) = EMBEDDED_SPECS[0];
        std::fs::remove_file(tmp.path().join(victim)).unwrap();
        assert!(!embedded_dir_is_current(tmp.path()));
    }

    #[test]
    #[cfg(unix)]
    fn write_embedded_specs_does_not_follow_destination_symlink() {
        // Pre-seed one of the target spec files as a symlink to an external
        // victim file. A `std::fs::write`-based writer would follow the
        // symlink and truncate the victim; the atomic temp-then-rename
        // path must replace the symlink in-place with a regular file and
        // leave the victim untouched.
        let tmp = TempDir::new().unwrap();
        let victim = tmp.path().join("victim.txt");
        std::fs::write(&victim, "DO NOT OVERWRITE").unwrap();

        let cache = tmp.path().join("cache");
        std::fs::create_dir_all(&cache).unwrap();
        // Pick the first embedded spec name as the attack target.
        let (target_name, _) = EMBEDDED_SPECS[0];
        let target = cache.join(target_name);
        std::os::unix::fs::symlink(&victim, &target).unwrap();

        write_embedded_specs(&cache).unwrap();

        // The victim's contents must be intact — `rename` replaced the
        // symlink itself, not the file it pointed at.
        let victim_after = std::fs::read_to_string(&victim).unwrap();
        assert_eq!(
            victim_after, "DO NOT OVERWRITE",
            "atomic_write must not follow a pre-seeded destination symlink"
        );
        // And the target is now a regular file holding the spec contents.
        let meta = std::fs::symlink_metadata(&target).unwrap();
        assert!(
            !meta.file_type().is_symlink(),
            "destination should have been replaced with a regular file"
        );
    }

    #[test]
    #[cfg(unix)]
    fn atomic_write_refuses_pre_seeded_temp_symlink() {
        // Core property: `create_new(true) + O_NOFOLLOW` on the temp path
        // refuses to open when the temp path already exists as a symlink.
        // Here we construct an `OpenOptions` identical to the one
        // `atomic_write` uses and confirm it fails with AlreadyExists when
        // pointed at a pre-existing symlink — so a same-user attacker who
        // pre-seeds the temp path cannot redirect our write to an arbitrary
        // victim.
        use std::os::unix::fs::OpenOptionsExt;

        let tmp = TempDir::new().unwrap();
        let victim = tmp.path().join("victim.txt");
        std::fs::write(&victim, "DO NOT OVERWRITE").unwrap();

        let tmp_path = tmp.path().join(".attacker-controlled.tmp");
        std::os::unix::fs::symlink(&victim, &tmp_path).unwrap();

        let err = std::fs::OpenOptions::new()
            .write(true)
            .create_new(true)
            .custom_flags(libc::O_NOFOLLOW)
            .mode(0o600)
            .open(&tmp_path)
            .expect_err("create_new + O_NOFOLLOW must refuse a pre-existing symlink");
        // create_new yields AlreadyExists when anything exists at the
        // path (symlink counts — O_NOFOLLOW doesn't dereference).
        assert_eq!(
            err.kind(),
            std::io::ErrorKind::AlreadyExists,
            "expected AlreadyExists, got {err:?}"
        );
        // Victim is untouched — the open failed before any write.
        assert_eq!(
            std::fs::read_to_string(&victim).unwrap(),
            "DO NOT OVERWRITE"
        );
    }

    #[test]
    fn atomic_write_cleans_up_temp_on_rename_error() {
        // If rename fails (e.g. dest parent is read-only, or dest is a
        // directory), the temp file must be removed — every post-create
        // error path must clean up, not just rename. We trigger this by
        // passing a dest that is itself a directory, which
        // `rename(file -> dir)` rejects.
        let tmp = TempDir::new().unwrap();
        let dest_dir = tmp.path().join("dest_is_dir");
        std::fs::create_dir_all(&dest_dir).unwrap();

        let err =
            atomic_write(&dest_dir, b"content", 0).expect_err("rename over a directory must fail");
        assert!(
            err.kind() != std::io::ErrorKind::NotFound,
            "rename error expected, not NotFound: {err:?}"
        );

        // No leftover temp files in the tmp dir — cleanup must have run.
        let leftovers: Vec<_> = std::fs::read_dir(tmp.path())
            .unwrap()
            .flatten()
            .filter_map(|e| e.file_name().into_string().ok())
            .filter(|n| n.starts_with(".dest_is_dir.tmp."))
            .collect();
        assert!(
            leftovers.is_empty(),
            "atomic_write must clean up its temp file on rename error, found: {leftovers:?}"
        );
    }

    #[test]
    #[cfg(unix)]
    fn write_embedded_specs_rechecks_symlink_after_create_dir_all() {
        // `materialize_embedded_specs_at` checks for a symlinked cache
        // dir up front, but `create_dir_all` + `read_dir` + subsequent
        // purge all re-traverse the path. If an attacker swaps the dir
        // for a symlink between the first check and the purge, the
        // purge walks through the link and deletes files outside the
        // cache. The post-create_dir_all re-check closes the simple
        // swap window: `write_embedded_specs` with a symlinked dir
        // must error out before any filesystem mutation inside the
        // link target.
        let tmp = TempDir::new().unwrap();
        let real_target = tmp.path().join("real_target");
        std::fs::create_dir_all(&real_target).unwrap();
        let canary = real_target.join("canary.json");
        std::fs::write(&canary, "UNTOUCHED").unwrap();

        let link = tmp.path().join("symlinked_cache");
        std::os::unix::fs::symlink(&real_target, &link).unwrap();

        let err = write_embedded_specs(&link)
            .expect_err("write_embedded_specs must refuse a symlinked cache dir");
        assert_eq!(err.kind(), std::io::ErrorKind::InvalidInput);

        // The symlink target must be untouched — the purge never ran.
        assert_eq!(std::fs::read_to_string(&canary).unwrap(), "UNTOUCHED");
        // And the symlink still points where it did — we didn't replace it.
        let meta = std::fs::symlink_metadata(&link).unwrap();
        assert!(meta.file_type().is_symlink());
    }

    #[test]
    #[cfg(unix)]
    fn materialize_embedded_specs_at_refuses_symlinked_cache_dir() {
        // When the cache dir itself is a symlink, materialisation must
        // bail out and return `None` without writing anything through the
        // link. The `write_embedded_specs` purge step would otherwise
        // follow the link and start deleting files outside the cache.
        let tmp = TempDir::new().unwrap();
        let real = tmp.path().join("real");
        std::fs::create_dir_all(&real).unwrap();
        let sneaky_target = tmp.path().join("not-our-cache");
        std::fs::create_dir_all(&sneaky_target).unwrap();
        let canary = sneaky_target.join("canary.json");
        std::fs::write(&canary, "UNTOUCHED").unwrap();

        let link = tmp.path().join("cache");
        std::os::unix::fs::symlink(&sneaky_target, &link).unwrap();

        let result = materialize_embedded_specs_at(&link);
        assert!(
            result.is_none(),
            "symlinked cache dir must be refused, got: {result:?}"
        );
        // The symlink target must not have been modified — no spec files
        // written, canary still present.
        assert!(canary.exists(), "canary file outside the cache was deleted");
        assert_eq!(std::fs::read_to_string(&canary).unwrap(), "UNTOUCHED");
        // The symlink must still be a symlink (we didn't replace it).
        let meta = std::fs::symlink_metadata(&link).unwrap();
        assert!(meta.file_type().is_symlink());
    }
}
