//! Embedded completion specs.
//!
//! ## Why this exists
//!
//! `ghost-complete` ships with 709 Fig-compatible completion specs baked
//! into the binary. The embedded payload is produced by the crate's
//! `build.rs`, which reads every `specs/*.json`, strips the
//! runtime-unused `js_source` field from generators, re-serialises each
//! spec compactly (no pretty-print whitespace), and writes the result to
//! `$OUT_DIR/specs-min/`. `EMBEDDED_SPECS` itself is generated by the
//! same script and `include!`d from `$OUT_DIR/embedded_specs.rs`.
//!
//! Originally these embedded specs only existed to be copied to disk by
//! `ghost-complete install`. That left a latent bug: a user who ran
//! `cargo install ghost-complete` and then launched `ghost-complete`
//! (without first running `install`) loaded zero specs and got no error
//! — autocomplete silently degraded to filesystem + history + `$PATH`
//! only.
//!
//! ## Runtime path (v0.12.4+)
//!
//! The embedded specs are now consumed in-memory by
//! [`crate::specs::SpecStore::load_with_embedded`] via
//! [`embedded_entries_with_aliases`]: the spec loader registers each
//! `(filename, contents, name_alias)` tuple as a lazy [`SpecSource::Embedded`]
//! entry whose JSON body is a `&'static str` slice into the binary. No disk
//! materialisation, no `.cache` write on first run, no version sentinel.
//!
//! Earlier versions (≤ v0.12.3) used [`embedded_cache_dir`] as a
//! materialisation target; [`purge_embedded_cache_if_present`] removes
//! that orphaned directory so upgraders don't keep a 25 MB stale copy
//! around indefinitely. `ghost-complete install` and `ghost-complete
//! uninstall` both invoke it.

use std::path::{Path, PathBuf};

// Generated by `build.rs` — spec JSON is minified and has the
// runtime-unused `js_source` field stripped from every generator to
// keep the embedded payload small. See the module doc-comment and
// `build.rs` for details.
include!(concat!(env!("OUT_DIR"), "/embedded_specs.rs"));

/// Look up an embedded spec's JSON contents by filename (e.g. `"git.json"`).
///
/// Returns `Some(contents)` when the binary ships with that spec. Used by
/// the runtime spec loader to read embedded specs in-memory without going
/// through the on-disk materialisation path.
pub fn embedded_spec_contents(filename: &str) -> Option<&'static str> {
    EMBEDDED_SPECS
        .iter()
        .find(|(name, _)| *name == filename)
        .map(|(_, contents)| *contents)
}

/// Iterate every embedded `(filename, contents, name_alias)` triple in
/// emit order. The alias is the `CompletionSpec.name` field captured at
/// build time when it differs from the filename stem; `None` otherwise.
///
/// This is the single source of truth for the runtime fallback path —
/// callers iterate it instead of materialising specs to disk first.
pub fn embedded_entries_with_aliases(
) -> impl Iterator<Item = (&'static str, &'static str, Option<&'static str>)> {
    EMBEDDED_SPECS.iter().zip(EMBEDDED_SPEC_ALIASES.iter()).map(
        |((filename, contents), (alias_filename, name_alias))| {
            debug_assert_eq!(
                *filename, *alias_filename,
                "EMBEDDED_SPECS and EMBEDDED_SPEC_ALIASES are emitted in the \
                 same order by build.rs; mismatch indicates a build-script bug"
            );
            (*filename, *contents, *name_alias)
        },
    )
}

/// Path of the legacy `~/.cache/ghost-complete/embedded-specs/` directory
/// where pre-v0.12.4 binaries materialised the embedded corpus on first
/// run. v0.12.4+ no longer writes here; the only remaining caller is
/// [`purge_embedded_cache_if_present`], which deletes the directory if a
/// previous version left it behind.
pub fn embedded_cache_dir() -> Option<PathBuf> {
    dirs::home_dir().map(|h| {
        h.join(".cache")
            .join("ghost-complete")
            .join("embedded-specs")
    })
}

/// Remove the legacy embedded-spec cache directory at `dir` if it exists.
///
/// Returns `Ok(Some(path))` when a directory was deleted, `Ok(None)`
/// when nothing needed cleanup (dir absent, path is not a directory, or
/// path is a symlink which we refuse to follow), and an error when deletion
/// failed.
///
/// Symlink safety: a same-user attacker who replaces the cache dir with
/// a symlink before `ghost-complete install` runs could otherwise
/// redirect `remove_dir_all` at any directory the user can write to. We
/// detect symlinks via `symlink_metadata` and refuse to act — leaving
/// the symlink intact for the user to investigate.
pub fn purge_embedded_cache_at(dir: &Path) -> std::io::Result<Option<PathBuf>> {
    let meta = match std::fs::symlink_metadata(dir) {
        Ok(m) => m,
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => return Ok(None),
        Err(e) => return Err(e),
    };
    if meta.file_type().is_symlink() {
        tracing::warn!(
            dir = %dir.display(),
            "legacy embedded-spec cache path is a symlink; refusing to remove"
        );
        return Ok(None);
    }
    if !meta.is_dir() {
        return Ok(None);
    }
    std::fs::remove_dir_all(dir)?;
    Ok(Some(dir.to_path_buf()))
}

/// Remove the legacy embedded-spec cache directory if it exists.
///
/// Returns `Ok(Some(path))` when a directory was deleted, `Ok(None)`
/// when nothing needed cleanup (no home dir, dir absent, or path is a
/// symlink which we refuse to follow), and an error when deletion failed.
pub fn purge_embedded_cache_if_present() -> std::io::Result<Option<PathBuf>> {
    let Some(dir) = embedded_cache_dir() else {
        return Ok(None);
    };
    purge_embedded_cache_at(&dir)
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    #[test]
    fn embedded_spec_aliases_aligns_with_specs() {
        assert_eq!(
            EMBEDDED_SPECS.len(),
            EMBEDDED_SPEC_ALIASES.len(),
            "EMBEDDED_SPECS and EMBEDDED_SPEC_ALIASES must have matching lengths"
        );
        for ((spec_name, _), (alias_name, _)) in
            EMBEDDED_SPECS.iter().zip(EMBEDDED_SPEC_ALIASES.iter())
        {
            assert_eq!(
                spec_name, alias_name,
                "EMBEDDED_SPECS / EMBEDDED_SPEC_ALIASES filename ordering must agree"
            );
        }
    }

    #[test]
    fn embedded_entries_with_aliases_yields_known_alias() {
        // appwrite.json declares `name: "index"` — the build.rs captures
        // it as a non-stem alias. Pin a known live entry so a future
        // refactor of the build script can't silently zero out the table.
        let appwrite = embedded_entries_with_aliases()
            .find(|(filename, _, _)| *filename == "appwrite.json")
            .expect("appwrite.json must ship in the embedded corpus");
        assert_eq!(appwrite.2, Some("index"));
    }

    #[test]
    fn embedded_spec_alias_manifest_matches_parsed_spec_names() {
        for (filename, contents, name_alias) in embedded_entries_with_aliases() {
            let stem = filename
                .strip_suffix(".json")
                .expect("embedded spec filenames end in .json");
            let parsed = crate::specs::parse_spec_checked_and_sanitized(contents)
                .unwrap_or_else(|e| panic!("embedded spec {filename} failed to parse: {e}"));
            let expected = (parsed.name != stem).then_some(parsed.name.as_str());
            assert_eq!(
                name_alias, expected,
                "embedded alias manifest disagrees with parsed CompletionSpec.name for {filename}"
            );
        }
    }

    #[test]
    fn load_with_embedded_resolves_non_stem_name_alias() {
        let result = crate::specs::SpecStore::load_with_embedded(&[])
            .expect("embedded corpus must register");
        let store = result.store;

        let by_stem = store
            .get("appwrite")
            .expect("appwrite stem must resolve through embedded corpus");
        assert_eq!(by_stem.name, "index");

        let by_alias = store
            .get("index")
            .expect("appwrite name alias must resolve through embedded corpus");
        assert_eq!(by_alias.name, "index");
        assert_eq!(
            by_stem.as_ref() as *const _,
            by_alias.as_ref() as *const _,
            "stem and name alias must resolve to the same parsed embedded spec"
        );
    }

    #[test]
    fn embedded_spec_contents_round_trips() {
        for (filename, contents) in EMBEDDED_SPECS {
            assert_eq!(embedded_spec_contents(filename), Some(*contents));
        }
        assert!(embedded_spec_contents("does-not-exist.json").is_none());
    }

    #[test]
    fn embedded_specs_slice_is_non_empty() {
        // If this ever fails it means the include_str! table got truncated
        // or the const was emptied — the runtime fallback would silently
        // load zero specs, defeating the binary-embedded fallback entirely.
        assert!(
            !EMBEDDED_SPECS.is_empty(),
            "EMBEDDED_SPECS must not be empty"
        );
        // Sanity: every entry must have a non-empty name and non-empty body.
        for (name, body) in EMBEDDED_SPECS {
            assert!(!name.is_empty(), "embedded spec has empty name");
            assert!(!body.is_empty(), "embedded spec {name} has empty body");
            assert!(
                name.ends_with(".json"),
                "embedded spec {name} should be a .json file"
            );
        }
    }

    #[test]
    fn embedded_specs_preserve_corrected_in_markers() {
        // `build.rs::strip_js_source` must NOT strip `_corrected_in`.
        // That marker surfaces generators that were previously mis-converted.
        //
        // WHY this test pins a total: a build-time regression that
        // incidentally dropped `_corrected_in` at any nesting depth would
        // not fail any existing test — every spec would still parse, every
        // generator would still load, but `ghost-complete doctor` would go
        // silent. Walk every embedded spec, count markers, compare to the
        // expected total.
        //
        // Expected count is hard-coded rather than derived from
        // `docs/coverage-baseline.json` because (a) the baseline file is
        // outside this crate and the test would then depend on the workspace
        // layout, and (b) the baseline's `corrected_generators` field is a
        // release-time snapshot that lags the live spec set. If you add or
        // remove `_corrected_in` markers in `specs/`, update this constant
        // and the baseline together in the same PR.
        const EXPECTED_CORRECTED_IN: usize = 171;

        fn count(v: &serde_json::Value) -> usize {
            match v {
                serde_json::Value::Object(map) => {
                    let here = usize::from(map.contains_key("_corrected_in"));
                    here + map.values().map(count).sum::<usize>()
                }
                serde_json::Value::Array(arr) => arr.iter().map(count).sum(),
                _ => 0,
            }
        }

        let total: usize = EMBEDDED_SPECS
            .iter()
            .map(|(name, body)| {
                let v: serde_json::Value = serde_json::from_str(body)
                    .unwrap_or_else(|e| panic!("embedded spec {name} is not valid JSON: {e}"));
                count(&v)
            })
            .sum();

        assert_eq!(
            total, EXPECTED_CORRECTED_IN,
            "embedded specs have {total} `_corrected_in` markers, expected {EXPECTED_CORRECTED_IN}. \
             If you changed a corrected generator, update EXPECTED_CORRECTED_IN and \
             docs/coverage-baseline.json together. If you did NOT intentionally change \
             corrections, build.rs::strip_js_source likely dropped the marker — check its \
             recursion."
        );
    }

    #[test]
    fn purge_embedded_cache_at_removes_directory() {
        let tmp = TempDir::new().unwrap();
        let cache = tmp.path().join("embedded-specs");
        std::fs::create_dir_all(&cache).unwrap();
        std::fs::write(cache.join("git.json"), "{}").unwrap();

        let purged = purge_embedded_cache_at(&cache).unwrap();

        assert_eq!(purged.as_deref(), Some(cache.as_path()));
        assert!(
            !cache.exists(),
            "legacy embedded cache directory must be removed"
        );
    }

    #[test]
    fn purge_embedded_cache_at_returns_none_when_dir_absent() {
        let tmp = TempDir::new().unwrap();
        let absent = tmp.path().join("never-existed");

        let purged = purge_embedded_cache_at(&absent).unwrap();

        assert!(purged.is_none());
        assert!(!absent.exists());
    }

    #[test]
    fn purge_embedded_cache_at_ignores_non_directory() {
        let tmp = TempDir::new().unwrap();
        let file = tmp.path().join("embedded-specs");
        std::fs::write(&file, "not a directory").unwrap();

        let purged = purge_embedded_cache_at(&file).unwrap();

        assert!(purged.is_none());
        assert_eq!(std::fs::read_to_string(&file).unwrap(), "not a directory");
    }

    /// A symlink at the cache-dir path must be left intact — `remove_dir_all`
    /// would otherwise delete files inside an attacker-controlled target.
    #[test]
    #[cfg(unix)]
    fn purge_embedded_cache_at_refuses_to_follow_symlink() {
        let tmp = TempDir::new().unwrap();
        let real = tmp.path().join("real");
        std::fs::create_dir_all(&real).unwrap();
        let canary = real.join("canary.txt");
        std::fs::write(&canary, "UNTOUCHED").unwrap();

        let link = tmp.path().join("link-cache");
        std::os::unix::fs::symlink(&real, &link).unwrap();

        let purged = purge_embedded_cache_at(&link).unwrap();

        assert!(purged.is_none());
        assert!(canary.exists());
        let after = std::fs::symlink_metadata(&link).unwrap();
        assert!(after.file_type().is_symlink());
    }
}
